# Generated by Django 5.2.17 on 2026-09-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="category",
            field=models.CharField(
                choices=[
                    ("pcb", "PCB design"),
                    ("3d", "3D modeling"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="location",
            field=models.CharField(blank=True, default="Remote", max_length=60),
        ),
        migrations.AddField(
            model_name="position",
            name="pay",
            field=models.CharField(
                blank=True,
                help_text='e.g. "$40 - $60 / hour". Leave empty to hide.',
                max_length=60,
            ),
        ),
    ]
