# Generated by Django 5.2.17 on 2026-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0002_position_category_position_location_position_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="test_form_url",
            field=models.URLField(
                blank=True,
                help_text="Google Form link. May contain {name}, {first_name}, {last_name}, {email} which are replaced with the logged-in user's details.",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="test_instructions",
            field=models.TextField(
                blank=True,
                help_text="Shown in the popup when the user clicks Apply. Line breaks are kept.",
            ),
        ),
    ]
