# Generated by Django 5.2.17 on 2026-09-27 13:57

from django.db import migrations, models

COUNTRIES = "United States, Canada, Brazil"
PAY = "$200 per task"


def set_countries_and_pay(apps, schema_editor):
    """Give every existing position the countries and pay requested."""
    Position = apps.get_model("positions", "Position")
    Position.objects.update(countries=COUNTRIES, pay=PAY)


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0003_position_test_form_url_position_test_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="countries",
            field=models.CharField(
                blank=True,
                help_text='Where applicants must live, e.g. "United States, Canada, Brazil".',
                max_length=255,
            ),
        ),
        migrations.RunPython(set_countries_and_pay, migrations.RunPython.noop),
    ]
