# Generated by Django 5.2.17 on 2026-09-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0004_position_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="category",
            field=models.CharField(
                choices=[
                    ("pcb", "PCB design"),
                    ("3d", "3D modeling"),
                    ("character", "3D character design"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=12,
            ),
        ),
    ]
