# Generated by Django 5.2.17 on 2026-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0005_alter_position_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="admin_note",
            field=models.TextField(
                blank=True, help_text="Shown to the applicant on their dashboard."
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="agreed_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_10", "Less than 10 hours / week"),
                    ("10_20", "10 - 20 hours / week"),
                    ("20_40", "20 - 40 hours / week"),
                    ("over_40", "40+ hours / week"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="application",
            name="id_verified",
            field=models.BooleanField(
                default=False,
                help_text="Tick after checking their ID.",
                verbose_name="ID verified",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="location",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="location (city, country)"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="motivation",
            field=models.TextField(blank=True, verbose_name="why they want to join"),
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="application",
            name="related_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="application",
            name="stage",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Apply"),
                    (2, "Qualification test"),
                    (3, "ID verification"),
                    (4, "Training"),
                    (5, "Project work"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("on_hold", "On hold"),
                    ("rejected", "Not selected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="in_progress",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="position",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("part_time", "Part-time"),
                    ("full_time", "Full-time"),
                ],
                default="contract",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="highlights",
            field=models.TextField(
                blank=True,
                help_text='Check list on the card, one per line, e.g. "Training provided".',
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Skills / experience needed, one per line."
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="why_apply",
            field=models.TextField(
                blank=True, help_text="Reasons to apply, one per line."
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="category",
            field=models.CharField(
                choices=[
                    ("pcb", "PCB design"),
                    ("3d", "3D modeling"),
                    ("character", "3D character design"),
                    ("annotation", "Data annotation"),
                    ("ai_training", "AI training data"),
                    ("evaluation", "AI/LLM evaluation"),
                    ("qa", "QA testing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="pay",
            field=models.CharField(
                blank=True,
                help_text='e.g. "$45/hr" or "$200 per task". Empty = hidden.',
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="responsibilities",
            field=models.TextField(blank=True, help_text="One per line."),
        ),
        migrations.AlterField(
            model_name="position",
            name="test_instructions",
            field=models.TextField(
                blank=True,
                help_text="Shown on the Qualification test page of the portal. Line breaks are kept.",
            ),
        ),
    ]
