# Generated by Django 5.2.17 on 2026-10-01 13:52

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    # Accounts created before email verification existed keep working.
    apps.get_model("accounts", "User").objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set when the user clicks the link in the verification email (or logs in with Google/Apple). Unverified users can't log in with a password.",
            ),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
