# Generated by Django 5.2.17 on 2026-09-30 17:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Doc, video, slides...",
                        max_length=1000,
                        verbose_name="link to the material",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text='e.g. "20 min"', max_length=40
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "pay_per_task",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Workers who see this project.",
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField(blank=True)),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="where to do the task"
                    ),
                ),
                (
                    "pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Empty = the project's pay per task.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="assigned",
                        max_length=10,
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, help_text="Shown to the worker."),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="portal.project",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="portal.trainingmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "module"), name="unique_training_completion"
                    )
                ],
            },
        ),
    ]
