# Generated by Django 5.2.17 on 2026-10-05 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0006_position_details_and_application_form"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "message",
                    models.TextField(
                        help_text="Plain text. An empty line starts a new paragraph. {name} is replaced by the person's first name."
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("selected", "Only the users selected below"),
                            ("verified", "All users with a verified email"),
                            ("all", "All active users"),
                            (
                                "applicants",
                                "Everyone who applied (to the position below, or to any position)",
                            ),
                        ],
                        default="selected",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending…"),
                            ("sent", "Sent"),
                            ("partly", "Sent with errors"),
                        ],
                        default="draft",
                        editable=False,
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("sent_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("failed_addresses", models.TextField(blank=True, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text='Used when "Send to" is "Everyone who applied". Empty = applicants of any position.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="positions.position",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Used when "Send to" is "Only the users selected below". Type a name or email to search.',
                        related_name="support_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "support email",
                "ordering": ["-created_at"],
            },
        ),
    ]
