# Generated by Django 5.2.17 on 2026-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportemail",
            name="format",
            field=models.CharField(
                choices=[
                    ("markdown", "Simple formatting (bold, links, lists, buttons)"),
                    ("html", "HTML (advanced)"),
                ],
                default="markdown",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supportemail",
            name="message",
            field=models.TextField(
                help_text="An empty line starts a new paragraph. {name} is replaced by the person's first name. Formatting: see the help above."
            ),
        ),
    ]
