# Generated by Django 5.2.17 on 2026-10-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Emails sent before this update didn't record who got them. Estimate it the way the email chose its
# recipients (audience), counting only accounts that existed at the time and leaving out failed addresses.


def fill_received_by(apps, schema_editor):
    SupportEmail = apps.get_model("mailing", "SupportEmail")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    for email in SupportEmail.objects.filter(status__in=["sent", "partly"], sent_at__isnull=False):
        users = User.objects.filter(is_active=True, date_joined__lte=email.sent_at)
        if email.audience == "selected":
            users = users.filter(pk__in=email.recipients.values("pk"))
        elif email.audience == "verified":
            users = users.filter(email_verified=True)
        elif email.audience == "applicants":
            users = users.filter(applications__created_at__lte=email.sent_at)
            if email.position_id:
                users = users.filter(applications__position_id=email.position_id)
        failed = [a for a in email.failed_addresses.split() if a]
        email.received_by.set(users.exclude(email__in=failed).distinct())


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_html_only"),
        ("positions", "0006_position_details_and_application_form"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportemail",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="mailing.supportemail",
                verbose_name="reused from",
            ),
        ),
        migrations.AddField(
            model_name="supportemail",
            name="received_by",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="received_support_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportemail",
            name="skip_already_received",
            field=models.BooleanField(
                default=True,
                help_text="Leave out everyone who already received the original email or an earlier copy of it.",
                verbose_name="skip people who already got it",
            ),
        ),
        migrations.RunPython(fill_received_by, migrations.RunPython.noop),
    ]
