# Generated by Django 5.2.17 on 2026-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("vendor", "Vendor"), ("user", "User")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("quote", models.TextField()),
                ("author_name", models.CharField(max_length=120)),
                (
                    "author_title",
                    models.CharField(
                        blank=True, help_text='e.g. "Hardware Engineer"', max_length=120
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="Company or vendor name", max_length=120
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide it from the site."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
